# https://aka.ms/yaml

trigger:
- master

variables:
  versionHadolint: 'v1.16.3'
  versionBuilder: '2022.01.0'

stages:
  - stage: lint
    jobs:
      - job: 'Hadolint'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: sudo docker pull hadolint/hadolint:$(versionHadolint)
          displayName: 'Install Hadolint'
        - script: |
            set -e
            shopt -s globstar
            for dockerfile in **/Dockerfile
            do
              echo "Linting: $dockerfile"
              sudo docker run --rm -i \
                -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
                hadolint/hadolint:$(versionHadolint) < "$dockerfile"
            done
          displayName: 'Run Hadolint'

      - job: 'JQ'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: sudo apt-get install -y jq
          displayName: 'Install JQ'
        - bash: |
            shopt -s globstar
            cat **/*.json | jq '.'
          displayName: 'Run JQ'
  - stage: build
    dependsOn: lint
    jobs:
      - template: .azure-pipelines/job-matrix.yml
        parameters:
          matrix:
            - addon: heimdall
              jobName: heimdall
              arch: '--armhf --amd64 --aarch64'
'
